// Generated by EmberScript 0.0.7
var set$ = Ember.set;
var get$ = Ember.get;
set$(window, 'Todos', Ember.Application.create());
set$(Todos, 'ApplicationAdapter', get$(DS, 'FixtureAdapter').extend());
