// Generated by EmberScript 0.0.7
var get$ = Ember.get;
var set$ = Ember.set;
get$(get$(window, 'Todos'), 'Router').map(function () {
  return this.resource('todos', { path: '/' });
});
set$(Todos, 'TodosRoute', Ember.Route.extend({
  model: function () {
    return get$(this, 'store').find('todo');
  }
}));
