// Generated by EmberScript 0.0.7
var get$ = Ember.get;
var set$ = Ember.set;
set$(Todos, 'Todo', get$(DS, 'Model').extend({
  title: DS.attr('string'),
  isCompleted: DS.attr('boolean')
}));
set$(get$(Todos, 'Todo'), 'FIXTURES', [
  {
    id: 1,
    title: 'Learn Ember.js',
    isCompleted: true
  },
  {
    id: 2,
    title: 'Go home',
    isCompleted: false
  },
  {
    id: 3,
    title: 'Profit!',
    isCompleted: false
  }
]);
